export enum UserType {
  SINDICO_RESIDENTE = 'SINDICO_RESIDENTE',
  SINDICO_PROFISSIONAL = 'SINDICO_PROFISSIONAL',
  ADMIN_IMOVEIS = 'ADMIN_IMOVEIS',
  PRESTADOR = 'PRESTADOR',
  ADMIN_PLATAFORMA = 'ADMIN_PLATAFORMA',
}

export enum RegimeTributario {
  SIMPLES = 'SIMPLES',
  LUCRO_PRESUMIDO = 'LUCRO_PRESUMIDO',
  LUCRO_REAL = 'LUCRO_REAL',
}

export enum ChamadoStatus {
  NOVO = 'NOVO',
  EM_ATENDIMENTO = 'EM_ATENDIMENTO',
  CONCLUIDO = 'CONCLUIDO',
}

export enum Prioridade {
  BAIXA = 'BAIXA',
  MEDIA = 'MEDIA',
  ALTA = 'ALTA',
}

export enum Escopo {
  ORCAMENTO = 'ORCAMENTO',
  SERVICO_IMEDIATO = 'SERVICO_IMEDIATO',
} 